"""Katip models init

Revision ID: 393a9e62d7c7
Revises: 
Create Date: 2026-07-21 14:57:48.253253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393a9e62d7c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('katip_brand_guides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_katip_brand_guides_tenant', 'katip_brand_guides', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_katip_brand_guides_tenant_id'), 'katip_brand_guides', ['tenant_id'], unique=False)
    op.create_table('katip_example_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_katip_example_articles_tenant', 'katip_example_articles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_katip_example_articles_tenant_id'), 'katip_example_articles', ['tenant_id'], unique=False)
    op.create_table('katip_revision_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('original_excerpt', sa.Text(), nullable=False),
    sa.Column('revised_excerpt', sa.Text(), nullable=False),
    sa.Column('pattern_tags', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_katip_revision_patterns_tenant', 'katip_revision_patterns', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_katip_revision_patterns_tenant_id'), 'katip_revision_patterns', ['tenant_id'], unique=False)
    op.create_table('katip_topics_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('topic_title', sa.String(length=500), nullable=False),
    sa.Column('target_keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_katip_topics_queue_status'), 'katip_topics_queue', ['status'], unique=False)
    op.create_index('ix_katip_topics_queue_status_tenant', 'katip_topics_queue', ['status', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_katip_topics_queue_tenant_id'), 'katip_topics_queue', ['tenant_id'], unique=False)
    op.create_table('plan_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('used_messages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_usages_month_key'), 'plan_usages', ['month_key'], unique=False)
    op.create_index(op.f('ix_plan_usages_tenant_id'), 'plan_usages', ['tenant_id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sector_prompts',
    sa.Column('sector_id', sa.String(length=100), nullable=False),
    sa.Column('base_prompt', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('sector_id')
    )
    op.create_index(op.f('ix_sector_prompts_sector_id'), 'sector_prompts', ['sector_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bot_active', sa.Boolean(), nullable=False),
    sa.Column('system_prompt_override', sa.String(length=1000), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=False),
    sa.Column('telegram_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_whatsapp_phone_number_id'), 'tenants', ['whatsapp_phone_number_id'], unique=True)
    op.create_table('katip_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['katip_topics_queue.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_katip_drafts_status'), 'katip_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_katip_drafts_tenant_id'), 'katip_drafts', ['tenant_id'], unique=False)
    op.create_index('ix_katip_drafts_tenant_status', 'katip_drafts', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_katip_drafts_topic_id'), 'katip_drafts', ['topic_id'], unique=False)
    op.create_table('katip_draft_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['katip_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['katip_draft_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'version_number', name='uq_katip_draft_version')
    )
    op.create_index('ix_katip_draft_versions_draft', 'katip_draft_versions', ['draft_id'], unique=False)
    op.create_index(op.f('ix_katip_draft_versions_draft_id'), 'katip_draft_versions', ['draft_id'], unique=False)
    op.create_table('katip_feedback_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_version_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['katip_draft_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_katip_feedback_notes_draft_version_id'), 'katip_feedback_notes', ['draft_version_id'], unique=False)
    op.create_table('katip_generation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_version_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_note_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['katip_draft_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_note_id'], ['katip_feedback_notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_katip_gen_log_draft_version', 'katip_generation_logs', ['draft_version_id'], unique=False)
    op.create_index('ix_katip_gen_log_feedback', 'katip_generation_logs', ['feedback_note_id'], unique=False)
    op.create_index(op.f('ix_katip_generation_logs_draft_version_id'), 'katip_generation_logs', ['draft_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_katip_generation_logs_draft_version_id'), table_name='katip_generation_logs')
    op.drop_index('ix_katip_gen_log_feedback', table_name='katip_generation_logs')
    op.drop_index('ix_katip_gen_log_draft_version', table_name='katip_generation_logs')
    op.drop_table('katip_generation_logs')
    op.drop_index(op.f('ix_katip_feedback_notes_draft_version_id'), table_name='katip_feedback_notes')
    op.drop_table('katip_feedback_notes')
    op.drop_index(op.f('ix_katip_draft_versions_draft_id'), table_name='katip_draft_versions')
    op.drop_index('ix_katip_draft_versions_draft', table_name='katip_draft_versions')
    op.drop_table('katip_draft_versions')
    op.drop_index(op.f('ix_katip_drafts_topic_id'), table_name='katip_drafts')
    op.drop_index('ix_katip_drafts_tenant_status', table_name='katip_drafts')
    op.drop_index(op.f('ix_katip_drafts_tenant_id'), table_name='katip_drafts')
    op.drop_index(op.f('ix_katip_drafts_status'), table_name='katip_drafts')
    op.drop_table('katip_drafts')
    op.drop_index(op.f('ix_tenants_whatsapp_phone_number_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sector_prompts_sector_id'), table_name='sector_prompts')
    op.drop_table('sector_prompts')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_plan_usages_tenant_id'), table_name='plan_usages')
    op.drop_index(op.f('ix_plan_usages_month_key'), table_name='plan_usages')
    op.drop_table('plan_usages')
    op.drop_index(op.f('ix_katip_topics_queue_tenant_id'), table_name='katip_topics_queue')
    op.drop_index('ix_katip_topics_queue_status_tenant', table_name='katip_topics_queue')
    op.drop_index(op.f('ix_katip_topics_queue_status'), table_name='katip_topics_queue')
    op.drop_table('katip_topics_queue')
    op.drop_index(op.f('ix_katip_revision_patterns_tenant_id'), table_name='katip_revision_patterns')
    op.drop_index('ix_katip_revision_patterns_tenant', table_name='katip_revision_patterns')
    op.drop_table('katip_revision_patterns')
    op.drop_index(op.f('ix_katip_example_articles_tenant_id'), table_name='katip_example_articles')
    op.drop_index('ix_katip_example_articles_tenant', table_name='katip_example_articles')
    op.drop_table('katip_example_articles')
    op.drop_index(op.f('ix_katip_brand_guides_tenant_id'), table_name='katip_brand_guides')
    op.drop_index('ix_katip_brand_guides_tenant', table_name='katip_brand_guides')
    op.drop_table('katip_brand_guides')
    # ### end Alembic commands ###
